### ISSUE TITLE
Cannot run in Godot 3.2.2

### ISSUE THREAD

**Issue by chrisleewoo** [nobuyukinyuu/gdsFM#2]
I'm not sure if there's a problem importing all the assets, I included the error output picture.
![Screenshot (5)](https://user-images.githubusercontent.com/24844439/91628555-bed07780-e975-11ea-8e28-618f3d132101.png)

**Comment by nobuyukinyuu** [comment]
The Mono build of Godot is required to run this project.

**Comment by nobuyukinyuu** [comment]
My apologies if I closed the issue prematurely;  if you still run into an issue with the Mono build, please let me know and I'll try to help.
